cluster: Rocket          # descriptive name to present to QCFractal server
loglevel: INFO
logfile: qcfractal-manager.log
update_frequency: 60.0

server:
  fractal_uri: ADD_LOCAL_URL_HERE      # e.g. https://qcarchive.molssi.org
  username: ADD_USERNAME_HERE
  password: ADD_PASSWORD_HERE
  verify: False

executors:
  local_executor:
    type: local
    max_workers: 1                # max number of workers to spawn
    cores_per_worker: 4          # cores per worker
    memory_per_worker: 10         # memory per worker, in GiB
    queue_tags:
      -  '*'
    environments:
      use_manager_environment: True
      conda:
        - qcfractal-compute-manager    # name of conda env used by worker; see below for example
