cluster: Rocket          # descriptive name to present to QCFractal server
loglevel: INFO
logfile: qcfractal-manager.log
update_frequency: 60.0

server:
  fractal_uri: http://10.211.116.206:7777      # e.g. https://qcarchive.molssi.org
  username: charlie_compute
  password: kuano123
  verify: False

executors:
  local_executor:
    type: local
    max_workers: 1                # max number of workers to spawn
    cores_per_worker: 4          # cores per worker
    memory_per_worker: 10         # memory per worker, in GiB
    queue_tags:
      - 'reorganization_energy_test'  #'conformers_submit'
    environments:
      use_manager_environment: True
      conda:
        -  qcarchive-worker-openff-psi4    # name of conda env used by worker; see below for example